"""Pre-flight readiness check for AIDLC.

Validates that a project has the necessary documentation and config
to run a productive planning session. Auto-creates .aidlc/ with defaults
if missing.
"""

import json
from pathlib import Path

# Document tiers with descriptions and suggestions
REQUIRED_DOCS = {
    "ROADMAP.md": {
        "purpose": "Phased delivery plan — what to build and in what order",
        "suggestion": (
            "Create a ROADMAP.md with phases, each containing:\n"
            "  - Clear deliverables and acceptance criteria\n"
            "  - Priority level (critical/high/medium/low)\n"
            "  - Dependencies between phases\n"
            "  Run 'aidlc init --with-docs' to get a template."
        ),
    },
}

RECOMMENDED_DOCS = {
    "README.md": {
        "purpose": "Project identity — what this project is and how to run it",
        "suggestion": "Add a README.md describing the project, setup instructions, and usage.",
    },
    "ARCHITECTURE.md": {
        "purpose": "System structure — components, data flow, key decisions",
        "suggestion": (
            "Run 'aidlc audit' to auto-generate one from your code,\n"
            "  or create it manually describing your system's components."
        ),
    },
    "DESIGN.md": {
        "purpose": "Patterns and conventions — coding standards, error handling approach",
        "suggestion": "Document your project's coding patterns so the planner follows them.",
    },
    "CLAUDE.md": {
        "purpose": "Direct AI instructions — project-specific rules for Claude",
        "suggestion": (
            "Add constraints like: 'always use TypeScript strict mode',\n"
            "  'never add new dependencies without noting in ROADMAP.md',\n"
            "  'follow the existing event-driven pattern'."
        ),
    },
}

OPTIONAL_DOCS = {
    "STATUS.md": {
        "purpose": "Current state of the codebase (auto-generated by 'aidlc audit')",
        "suggestion": "Run 'aidlc audit' to generate this automatically.",
    },
    "planning/": {
        "purpose": "Constraints, checklists, milestones",
        "suggestion": "Add planning docs for constraints or phase milestones.",
    },
    "specs/": {
        "purpose": "Feature specifications with detailed requirements",
        "suggestion": "Add feature specs for complex features the planner should reference.",
    },
    "design/": {
        "purpose": "Error handling strategy, testing strategy, patterns",
        "suggestion": "Document testing and error handling approaches.",
    },
    "docs/": {
        "purpose": "API reference, glossary, guides",
        "suggestion": "Add reference docs the planner can consult during implementation.",
    },
}


class PrecheckResult:
    """Result of a precheck run."""

    def __init__(self):
        self.config_created = False
        self.config_existed = True
        self.required_missing: list[str] = []
        self.required_found: list[str] = []
        self.recommended_missing: list[str] = []
        self.recommended_found: list[str] = []
        self.optional_missing: list[str] = []
        self.optional_found: list[str] = []
        self.project_type: str = "unknown"
        self.has_source_code: bool = False

    @property
    def ready(self) -> bool:
        """True if all required docs are present."""
        return len(self.required_missing) == 0

    @property
    def score(self) -> str:
        """Readiness rating."""
        total = (
            len(self.required_found) + len(self.recommended_found) + len(self.optional_found)
        )
        possible = (
            len(REQUIRED_DOCS) + len(RECOMMENDED_DOCS) + len(OPTIONAL_DOCS)
        )
        if not self.ready:
            return "not ready"
        if total >= possible * 0.7:
            return "excellent"
        if total >= possible * 0.4:
            return "good"
        return "minimal"


def run_precheck(project_root: Path, auto_init: bool = True) -> PrecheckResult:
    """Run pre-flight checks on a project.

    Args:
        project_root: Path to the project directory
        auto_init: If True, create .aidlc/ with defaults when missing

    Returns:
        PrecheckResult with findings
    """
    result = PrecheckResult()
    aidlc_dir = project_root / ".aidlc"

    # Auto-create .aidlc/ if missing
    if not aidlc_dir.exists() and auto_init:
        _auto_init_aidlc(project_root)
        result.config_created = True
        result.config_existed = False
    elif not (aidlc_dir / "config.json").exists() and auto_init:
        _auto_init_aidlc(project_root)
        result.config_created = True
        result.config_existed = False

    # Detect project type
    from .scanner import PROJECT_INDICATORS
    detected = []
    for filename, ptype in PROJECT_INDICATORS.items():
        if (project_root / filename).exists():
            detected.append(ptype)
    result.project_type = ", ".join(sorted(set(detected))) if detected else "unknown"

    # Check for source code
    source_extensions = {".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs", ".java", ".rb"}
    for entry in project_root.iterdir():
        if entry.is_dir() and entry.name not in {
            "node_modules", ".git", "venv", ".venv", "__pycache__", ".aidlc", "dist", "build"
        } and not entry.name.startswith("."):
            for f in entry.rglob("*"):
                if f.is_file() and f.suffix in source_extensions:
                    result.has_source_code = True
                    break
            if result.has_source_code:
                break

    # Check required docs
    for doc_name in REQUIRED_DOCS:
        if (project_root / doc_name).exists():
            result.required_found.append(doc_name)
        else:
            result.required_missing.append(doc_name)

    # Check recommended docs
    for doc_name in RECOMMENDED_DOCS:
        if (project_root / doc_name).exists():
            result.recommended_found.append(doc_name)
        else:
            result.recommended_missing.append(doc_name)

    # Check optional docs (some are directories)
    for doc_name in OPTIONAL_DOCS:
        path = project_root / doc_name
        if doc_name.endswith("/"):
            exists = path.exists() and path.is_dir() and any(path.iterdir())
        else:
            exists = path.exists()
        if exists:
            result.optional_found.append(doc_name)
        else:
            result.optional_missing.append(doc_name)

    return result


def _auto_init_aidlc(project_root: Path):
    """Create .aidlc/ directory with default config."""
    aidlc_dir = project_root / ".aidlc"
    aidlc_dir.mkdir(exist_ok=True)
    (aidlc_dir / "issues").mkdir(exist_ok=True)
    (aidlc_dir / "runs").mkdir(exist_ok=True)
    (aidlc_dir / "reports").mkdir(exist_ok=True)

    config_path = aidlc_dir / "config.json"
    if not config_path.exists():
        default_config = {
            "plan_budget_hours": 4,
            "checkpoint_interval_minutes": 15,
            "claude_model": "opus",
            "max_implementation_attempts": 3,
            "run_tests_command": None,
        }
        with open(config_path, "w") as f:
            json.dump(default_config, f, indent=2)

    # Add to .gitignore
    gitignore = project_root / ".gitignore"
    ignore_entry = "\n# AIDLC working directory\n.aidlc/runs/\n.aidlc/reports/\n"
    if gitignore.exists():
        content = gitignore.read_text()
        if ".aidlc/" not in content:
            with open(gitignore, "a") as f:
                f.write(ignore_entry)
    elif not gitignore.exists():
        gitignore.write_text(ignore_entry.lstrip())
